# Originally copied from: https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/fluentd-gcp
# Also see the post: http://blog.kubernetes.io/2015/06/cluster-level-logging-with-kubernetes.html

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-cloud-logging
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
    spec:
      serviceAccountName: fluentd-cloud-logging
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
      dnsPolicy: Default
      containers:
      - name: fluentd-cloud-logging
        image: mumoshu/kube-fluentd:0.14.22-0.9.9
        resources:
          limits:
            memory: 200Mi
          requests:
        # Any change here should be accompanied by a proportional change in CPU
        # requests of other per-node add-ons (e.g. kube-proxy).
            cpu: 80m
            memory: 200Mi
        env:
        - name: FLUENTD_ARGS
          value: -v
        - name: GOOGLE_FLUENTD_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              name: fluentd
              key: private.key.id
        - name: GOOGLE_FLUENTD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: fluentd
              key: private.key
        - name: GOOGLE_FLUENTD_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: fluentd
              key: project.id
        - name: GOOGLE_FLUENTD_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: fluentd
              key: client.email
        - name: GOOGLE_FLUENTD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: fluentd
              key: client.id
        - name: GOOGLE_FLUENTD_CLIENT_X509_CERT_URL
          valueFrom:
            secretKeyRef:
              name: fluentd
              key: client.x509.cert.url
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: mntsda1
          mountPath: /mnt/sda1
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: mntsda1
        hostPath:
          path: /mnt/sda1
