DOCKER_IMAGE ?= mumoshu/kube-fluentd
DOCKER_TAG ?= latest

build:
	docker build -t $(DOCKER_IMAGE):$(DOCKER_TAG) .

docker-run: DOCKER_CMD ?=
docker-run:
	docker run --rm -it \
	  -e GOOGLE_FLUENTD_PRIVATE_KEY_ID="$(GOOGLE_FLUENTD_PRIVATE_KEY_ID)" \
	  -e GOOGLE_FLUENTD_PRIVATE_KEY="$(GOOGLE_FLUENTD_PRIVATE_KEY)" \
	  -e GOOGLE_FLUENTD_PROJECT_ID="$(GOOGLE_FLUENTD_PROJECT_ID)" \
	  -e GOOGLE_FLUENTD_CLIENT_EMAIL="$(GOOGLE_FLUENTD_CLIENT_EMAIL)" \
	  -e GOOGLE_FLUENTD_CLIENT_ID="$(GOOGLE_FLUENTD_CLIENT_ID)" \
	  -e GOOGLE_FLUENTD_CLIENT_X509_CERT_URL="$(GOOGLE_FLUENTD_CLIENT_X509_CERT_URL)" \
	$(DOCKER_IMAGE):$(DOCKER_TAG) $(DOCKER_CMD)
