#!/usr/bin/with-contenv sh

confd_root=/etc/confd
fluentd_root=/fluentd
for f in $(cd ${fluentd_root} && find ${fluentd_root}${confd_root}/templates -name \*.conf.tmpl); do
  escaped_fluentd_root=$(echo ${fluentd_root} | sed -e 's/\//\\\//g')
  tmpl=$(echo "$f" | sed -e "s/${escaped_fluentd_root}//")
  dest_base=$(basename -s .tmpl ${tmpl})
  dest=${fluentd_root}/etc/conf.d/${dest_base}
  confd_conf=${confd_root}/conf.d/${dest_base}.toml

  echo copying $f to $tmpl

  cp $f $tmpl

  echo generating $confd_conf to generate $dest from $tmpl

  echo '[template]
src = '\"$(basename $tmpl)\"'
dest = '\"$dest\"'
keys = [
    "/dd/api/key",
    "/dd/service",
    "/dd/source",
    "/dd/sourcecategory",
    "/dd/tags",
    "/fluentd/out/kubeuser/buffer/overflow/action",
    "/fluentd/out/kubeuser/buffer/chunk/limit/size",
    "/fluentd/out/kubeuser/buffer/total/limit/size",
    "/fluentd/out/kubeuser/buffer/flush/interval",
    "/fluentd/out/kubeuser/buffer/retry/max/interval",
    "/fluentd/out/kubeuser/retry/forever",
    "/fluentd/out/kubeuser/retry/max/times",
    "/fluentd/out/kubeuser/flush/thread/count",
    "/fluentd/out/kubesys/buffer/overflow/action",
    "/fluentd/out/kubesys/buffer/chunk/limit/size",
    "/fluentd/out/kubesys/buffer/total/limit/size",
    "/fluentd/out/kubesys/buffer/flush/interval",
    "/fluentd/out/kubesys/buffer/retry/max/interval",
    "/fluentd/out/kubesys/retry/forever",
    "/fluentd/out/kubesys/retry/max/times",
    "/fluentd/out/kubesys/flush/thread/count",
]' > $confd_conf

  ls -lah $tmpl
  cat $tmpl
  ls -lah $confd_conf
  cat $confd_conf
done
